#[derive(Debug, Clone, Copy)]
pub enum ZOrdering {
    Orbit,
    OrbitLabels,
    Planet,
    Factory,
    Shipscope,
    ThrustParticles,
    Blueprint,
    EditorInteriorPart,
    EditorPipe,
    EditorPipeJoint,
    EditorTankFill,
    EditorItemBackground,
    EditorItem,
    EditorStructuralPart,
    EditorExteriorPart,
    EditorConnGroupHighlight,
    EditorConflictHighlight,
    EditorMouseoverPartHighlight,
    EditorConbot,
    EditorWeldingParticles,
    EditorCursor,
    Text,
    HudIcon,
    HudAngularMomentum,
    ScaleIndicator,
    Transforms,
    Waypoints,
    Ui,
    Ui2,
    Ui3,
    Window(u32, u32),
    Debug,
    Debug2,
}

impl ZOrdering {
    pub fn as_u32(&self) -> i32 {
        match self {
            ZOrdering::Orbit => 0,
            ZOrdering::OrbitLabels => 1,
            ZOrdering::Planet => 2,
            ZOrdering::Factory => 3,
            ZOrdering::Shipscope => 4,
            ZOrdering::ThrustParticles => 5,
            ZOrdering::Blueprint => 6,
            ZOrdering::EditorInteriorPart => 7,
            ZOrdering::EditorPipe => 8,
            ZOrdering::EditorPipeJoint => 9,
            ZOrdering::EditorTankFill => 10,
            ZOrdering::EditorItemBackground => 11,
            ZOrdering::EditorItem => 12,
            ZOrdering::EditorStructuralPart => 13,
            ZOrdering::EditorExteriorPart => 14,
            ZOrdering::EditorConnGroupHighlight => 15,
            ZOrdering::EditorConflictHighlight => 16,
            ZOrdering::EditorMouseoverPartHighlight => 17,
            ZOrdering::EditorConbot => 18,
            ZOrdering::EditorWeldingParticles => 19,
            ZOrdering::EditorCursor => 20,
            ZOrdering::Text => 21,
            ZOrdering::HudIcon => 22,
            ZOrdering::HudAngularMomentum => 23,
            ZOrdering::ScaleIndicator => 24,
            ZOrdering::Transforms => 25,
            ZOrdering::Waypoints => 26,
            ZOrdering::Ui => 27,
            ZOrdering::Ui2 => 28,
            ZOrdering::Ui3 => 29,
            ZOrdering::Window(n, l) => (30 + n * 100 + l) as i32,
            ZOrdering::Debug => 45,
            ZOrdering::Debug2 => 46,
        }
    }

    pub fn as_f32(&self) -> f32 {
        self.as_u32() as f32 / 100.0
    }
}
