[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy_dev_tools = "0.15.0"
bevy_vector_shapes = "0.9.2"
chrono = "0.4.39"
rand = "0.8.5"
rand_chacha = "0.3.1"
starling = { path = "../starling" }
