[package]
name = "train_game"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-iterator = "2.3.0"
glfw = "0.59.0"
glm = "0.3.0"
kira = "0.12.3"
pollster = "1.0.1"
rand = "0.10.2"
rend = { path = "../rend" }
bary_ui = { path = "../bary_ui" }
bary_core = { path = "../bary_core" }
bary_input = { path = "../bary_input" }
bary_ipc = { path = "../bary_ipc" }
bary_sim = { path = "../bary_sim" }
bary_orbital = { path = "../bary_orbital" }
rdev = { version = "0.5.3", features = ["serde", "serialize"] }
glam = { version = "0.30.9", features = ["serde"] }
bincode = "1.3.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
splines = "5.0.0"
noise = "0.9.0"
wgpu = "23.0.1"
log = "0.4.31"
simple_logger = "5.2.0"

[[bin]]
name = "choochoo"
path = "src/main.rs"
