[package]
name = "rend_client"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-iterator = "2.3.0"
glfw = "0.59.0"
glm = "0.3.0"
kira = "0.12.3"
pollster = "1.0.1"
rand = "0.10.2"
rend = { path = "../rend" }
bary_ui = { path = "../bary_ui" }
bary_core = { path = "../bary_core" }
bary_input = { path = "../bary_input" }
bary_ipc = { path = "../bary_ipc" }
bary_sim = { path = "../bary_sim" }
bary_orbital = { path = "../bary_orbital" }
rdev = { version = "0.5.3", features = ["serde", "serialize"] }
glam = { version = "0.30.9", features = ["serde"] }

[[bin]]
name = "kira_test"
path = "src/kira_test.rs"

[[bin]]
name = "choochoo"
path = "src/main.rs"
