[package]
name = "starling"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
bevy = "0.15.0"
bevy_ecs = "0.15.0"
chrono = "0.4.39"
csv = "1.3.1"
rand = "0.8.5"
uom = "0.36.0"

[[bin]]
name = "export_signals"
path = "bin/export_signals.rs"
