use crate::scenes::{CursorMode, ThrottleLevel};
use starling::prelude::{GroupId, OrbiterId, PartLayer, PlanetId};
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OnClick {
    Orbiter(OrbiterId),
    Exit,
    Save,
    Load,
    ToggleDrawMode,
    ClearTracks,
    CreateGroup,
    DisbandGroup(GroupId),
    ClearOrbits,
    CurrentBody(PlanetId),
    SelectedCount,
    AutopilotingCount,
    PilotOrbiter,
    Group(GroupId),
    TogglePause,
    World,
    SimSpeed(i32),
    GlobalOrbit(usize),
    DeleteOrbit(usize),
    DeleteOrbiter,
    ClearMission,
    CommitMission,
    CursorMode(CursorMode),
    GoToScene(usize),
    ThrottleLevel(ThrottleLevel),
    SetTarget(OrbiterId),
    SetPilot(OrbiterId),
    ClearTarget,
    ClearPilot,
    SwapOwnshipTarget,
    AddToFavorites(OrbiterId),
    RemoveFromFavorites(OrbiterId),
    SelectPart(String),
    ToggleLayer(PartLayer),
    LoadVehicle(PathBuf),
    DismissExitDialog,
    ConfirmExitDialog,
    TogglePartsMenuCollapsed,
    ToggleVehiclesMenuCollapsed,
    ToggleLayersMenuCollapsed,
    ToggleVehicleInfo,
    IncrementThrottle(i32),
    OpenNewCraft,
    WriteVehicleToImage,
    RotateCraft,
    NormalizeCraft,
    ToggleThruster(usize),
    ReloadGame,
    Nullopt,
}
