[package]
name = "bary_raylib"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0"
raylib = "5.5.1"
bary_core = { path = "../bary_core" }
bary_ui = { path = "../bary_ui" }
rdev = "0.5.3"
crossbeam-queue = "0.3.12"
enum-iterator = "2.3.0"
steamworks = "0.12.2"
renet = "2.0.0"
renet_netcode = "2.0.0"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3.3"
log = "0.4.29"
env_logger = "0.11.9"
simple_logger = "5.2.0"
chrono = { version = "0.4.44", features = ["serde"] }
serde_yaml = "0.9.34"
toml = "1.0.3"
early_returns = "0.4.0"
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
md5 = "0.8.0"
rfd = "0.17.2"
image = "0.25.10"

[[bin]]
name = "main"
path = "bin/main.rs"

[[bin]]
name = "kb"
path = "bin/kb.rs"

[[bin]]
name = "steam"
path = "bin/steam.rs"

[[bin]]
name = "server"
path = "bin/server.rs"

[[bin]]
name = "traj"
path = "bin/traj.rs"

[[bin]]
name = "ship2png"
path = "bin/ship2png.rs"

[[bin]]
name = "gridventory"
path = "bin/gridventory.rs"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
