[values.58]
on = true
status = "Running"
ticks_this_cycle = 0
ticks_per_cycle = 5
fired_this_tick = true
iters = 200
prototype = 6
command_queue = []

[values.58.vehicle_control]
attitude = 0.0

[values.58.vehicle_control.plus_x]
use_rcs = false
throttle = 0.0

[values.58.vehicle_control.plus_y]
use_rcs = false
throttle = 0.0

[values.58.vehicle_control.neg_x]
use_rcs = false
throttle = 0.0

[values.58.vehicle_control.neg_y]
use_rcs = false
throttle = 0.0

[values.152]
on = true
status = "Running"
ticks_this_cycle = 0
ticks_per_cycle = 5
fired_this_tick = true
iters = 200
prototype = 6
command_queue = []

[values.152.vehicle_control]
attitude = 0.0

[values.152.vehicle_control.plus_x]
use_rcs = false
throttle = 0.0

[values.152.vehicle_control.plus_y]
use_rcs = false
throttle = 0.0

[values.152.vehicle_control.neg_x]
use_rcs = false
throttle = 0.0

[values.152.vehicle_control.neg_y]
use_rcs = false
throttle = 0.0

[values.244]
on = true
status = "Running"
ticks_this_cycle = 0
ticks_per_cycle = 5
fired_this_tick = true
iters = 200
prototype = 6
command_queue = []

[values.244.vehicle_control]
attitude = 0.0

[values.244.vehicle_control.plus_x]
use_rcs = false
throttle = 0.0

[values.244.vehicle_control.plus_y]
use_rcs = false
throttle = 0.0

[values.244.vehicle_control.neg_x]
use_rcs = false
throttle = 0.0

[values.244.vehicle_control.neg_y]
use_rcs = false
throttle = 0.0
