[[values.38]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.39]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.45]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.46]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.46.filter]
Item = "H2"

[[values.50]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.50.filter]
Item = "H2"

[[values.52]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.52.filter]
Item = "H2"

[[values.55]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.56]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.56.filter]
Item = "H2"

[[values.59]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.59.filter]
Item = "H2"

[[values.60]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.60.filter]
Item = "H2"

[[values.63]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.64]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.64.filter]
Item = "H2"

[[values.65]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[0, 0], [3, 3]]

[[values.65]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[3, 0], [6, 3]]

[[values.65]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[0, 3], [3, 6]]

[[values.65]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[3, 3], [6, 6]]

[[values.67]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.69]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.70]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.70.filter]
Item = "H2"

[[values.76]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.84]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.84.filter]
Item = "H2"

[[values.88]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.88.filter]
Item = "H2"

[[values.90]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.90.filter]
Item = "H2"

[[values.95]]
capacity = 150000000
is_fluid = false
location = [[2, 1], [3, 2]]

[values.95.filter]
Item = "H2"

[[values.96]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.98]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.98.filter]
Item = "H2"

[[values.99]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.99.filter]
Item = "H2"

[[values.103]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.106]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.106.filter]
Item = "H2"

[[values.108]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.111]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.112]]
capacity = 150000000
is_fluid = false
location = [[2, 1], [3, 2]]

[values.112.filter]
Item = "H2"

[[values.114]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.114.filter]
Item = "H2"

[[values.117]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.119]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.120]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[0, 0], [3, 3]]

[[values.120]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[3, 0], [6, 3]]

[[values.120]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[0, 3], [3, 6]]

[[values.120]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[3, 3], [6, 6]]

[[values.125]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.126]]
capacity = 100000000
filter = "Any"
is_fluid = false
location = [[0, 0], [1, 1]]

[[values.126]]
capacity = 100000000
filter = "Any"
is_fluid = true
location = [[0, 1], [1, 2]]

[[values.126]]
capacity = 100000000
filter = "Any"
is_fluid = false
location = [[0, 2], [1, 3]]

[[values.126]]
capacity = 100000000
filter = "Any"
is_fluid = true
location = [[3, 4], [4, 5]]

[[values.126]]
capacity = 100000000
filter = "Any"
is_fluid = true
location = [[3, 5], [4, 6]]

[[values.131]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.132]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.132.filter]
Item = "H2"

[[values.133]]
capacity = 100000000
filter = "Any"
is_fluid = false
location = [[0, 0], [1, 1]]

[[values.133]]
capacity = 100000000
filter = "Any"
is_fluid = true
location = [[0, 1], [1, 2]]

[[values.133]]
capacity = 100000000
filter = "Any"
is_fluid = false
location = [[0, 2], [1, 3]]

[[values.133]]
capacity = 100000000
filter = "Any"
is_fluid = true
location = [[3, 4], [4, 5]]

[[values.133]]
capacity = 100000000
filter = "Any"
is_fluid = true
location = [[3, 5], [4, 6]]

[[values.134]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.174]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.174.filter]
Item = "H2"

[[values.175]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[0, 0], [3, 3]]

[[values.175]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[3, 0], [6, 3]]

[[values.175]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[0, 3], [3, 6]]

[[values.175]]
capacity = 1200000000
filter = "Solid"
is_fluid = false
location = [[3, 3], [6, 6]]

[[values.176]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.176.filter]
Item = "H2"

[[values.178]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.182]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.182.filter]
Item = "H2"

[[values.184]]
capacity = 150000000
is_fluid = false
location = [[2, 1], [3, 2]]

[values.184.filter]
Item = "H2"

[[values.186]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.186.filter]
Item = "H2"

[[values.187]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.187.filter]
Item = "H2"

[[values.188]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.188.filter]
Item = "H2"

[[values.192]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.193]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.195]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.195.filter]
Item = "H2"

[[values.196]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.196.filter]
Item = "H2"

[[values.201]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.201]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[4, 0], [6, 4]]

[[values.216]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.219]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.222]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.225]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.225.filter]
Item = "H2"

[[values.234]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.237]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.237.filter]
Item = "H2"

[[values.238]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.238.filter]
Item = "H2"

[[values.242]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.242.filter]
Item = "H2"

[[values.243]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.243.filter]
Item = "H2"

[[values.244]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.244.filter]
Item = "H2"

[[values.245]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.245.filter]
Item = "H2"

[[values.246]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.246.filter]
Item = "H2"

[[values.247]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.247.filter]
Item = "H2"

[[values.249]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.250]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.251]]
capacity = 14000000000
filter = "Solid"
is_fluid = false
location = [[1, 1], [23, 9]]

[[values.252]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.252.filter]
Item = "H2"

[[values.254]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.254.filter]
Item = "H2"

[[values.255]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.255.filter]
Item = "H2"

[[values.257]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.257.filter]
Item = "H2"

[[values.267]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.273]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.273.filter]
Item = "H2"

[[values.274]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.274.filter]
Item = "H2"

[[values.276]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.276.filter]
Item = "H2"

[[values.279]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.279.filter]
Item = "H2"

[[values.280]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.280.filter]
Item = "H2"

[[values.282]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.282.filter]
Item = "H2"

[[values.283]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.283.filter]
Item = "H2"

[[values.286]]
capacity = 14000000000
filter = "Solid"
is_fluid = false
location = [[1, 1], [23, 9]]

[[values.288]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.288.filter]
Item = "H2"

[[values.295]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.295.filter]
Item = "H2"

[[values.296]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.297]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.297.filter]
Item = "H2"

[[values.300]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.300.filter]
Item = "H2"

[[values.302]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.302.filter]
Item = "H2"

[[values.306]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.306.filter]
Item = "H2"

[[values.307]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.307.filter]
Item = "H2"

[[values.309]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.311]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.311.filter]
Item = "H2"

[[values.313]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.313.filter]
Item = "H2"

[[values.320]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.320.filter]
Item = "H2"

[[values.324]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.324.filter]
Item = "H2"

[[values.329]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.330]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.330.filter]
Item = "H2"

[[values.332]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.332.filter]
Item = "H2"

[[values.334]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.334.filter]
Item = "H2"

[[values.339]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.339.filter]
Item = "H2"

[[values.340]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.340.filter]
Item = "H2"

[[values.341]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.344]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.344.filter]
Item = "H2"

[[values.345]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.345.filter]
Item = "H2"

[[values.346]]
capacity = 14000000000
filter = "Solid"
is_fluid = false
location = [[1, 1], [23, 9]]

[[values.348]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.348.filter]
Item = "H2"

[[values.352]]
capacity = 14000000000
filter = "Solid"
is_fluid = false
location = [[1, 1], [23, 9]]

[[values.354]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.354.filter]
Item = "H2"

[[values.358]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.361]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.361.filter]
Item = "H2"

[[values.362]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.362.filter]
Item = "H2"

[[values.364]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.373]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.373.filter]
Item = "H2"

[[values.374]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.374.filter]
Item = "H2"

[[values.375]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.375.filter]
Item = "H2"

[[values.378]]
capacity = 14000000000
filter = "Solid"
is_fluid = false
location = [[1, 1], [23, 9]]

[[values.385]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.385.filter]
Item = "H2"

[[values.387]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.387.filter]
Item = "H2"

[[values.392]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.392.filter]
Item = "H2"

[[values.393]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.393.filter]
Item = "H2"

[[values.395]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.395.filter]
Item = "H2"

[[values.402]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.402.filter]
Item = "H2"

[[values.407]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.407.filter]
Item = "H2"

[[values.408]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.409]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.409.filter]
Item = "H2"

[[values.410]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.415]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.415.filter]
Item = "H2"

[[values.416]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.416.filter]
Item = "H2"

[[values.418]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.419]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.419.filter]
Item = "H2"

[[values.421]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.423]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.425]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.425.filter]
Item = "H2"

[[values.428]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.429]]
capacity = 14000000000
filter = "Solid"
is_fluid = false
location = [[1, 1], [23, 9]]

[[values.435]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.435.filter]
Item = "H2"

[[values.436]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.436.filter]
Item = "H2"

[[values.438]]
capacity = 1200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [4, 4]]

[[values.440]]
capacity = 300000000
is_fluid = false
location = [[5, 1], [6, 2]]

[values.440.filter]
Item = "H2"

[[values.441]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.442]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.442.filter]
Item = "H2"

[[values.444]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.444.filter]
Item = "H2"

[[values.447]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.447.filter]
Item = "H2"

[[values.450]]
capacity = 520000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 4]]

[[values.451]]
capacity = 20000000
is_fluid = false
location = [[0, 0], [1, 1]]

[values.451.filter]
Item = "H2"

[[values.453]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.454]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.455]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.456]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.457]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.458]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.459]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]

[[values.460]]
capacity = 200000000
filter = "Liquid"
is_fluid = true
location = [[0, 0], [2, 2]]
