[values.46.cycle]
on = 900
off = 1100
delay = 0

[values.50.cycle]
on = 900
off = 1100
delay = 400

[values.52.cycle]
on = 900
off = 1100
delay = 800

[values.59.cycle]
on = 900
off = 1100
delay = 1200

[values.60.cycle]
on = 900
off = 1100
delay = 1600

[values.64.cycle]
on = 900
off = 1100
delay = 0

[values.84.cycle]
on = 900
off = 1100
delay = 400

[values.88.cycle]
on = 900
off = 1100
delay = 800

[values.90.cycle]
on = 900
off = 1100
delay = 1200

[values.98.cycle]
on = 900
off = 1100
delay = 1600

[values.106.cycle]
on = 900
off = 1100
delay = 0

[values.114.cycle]
on = 900
off = 1100
delay = 400

[values.138.cycle]
on = 900
off = 1100
delay = 800

[values.140.cycle]
on = 900
off = 1100
delay = 1200

[values.146.cycle]
on = 900
off = 1100
delay = 1600

[values.150.cycle]
on = 900
off = 1100
delay = 0

[values.151.cycle]
on = 900
off = 1100
delay = 400

[values.152.cycle]
on = 900
off = 1100
delay = 800

[values.159.cycle]
on = 900
off = 1100
delay = 1200

[values.160.cycle]
on = 900
off = 1100
delay = 1600

[values.178.cycle]
on = 900
off = 1100
delay = 0

[values.190.cycle]
on = 900
off = 1100
delay = 400

[values.191.cycle]
on = 900
off = 1100
delay = 800

[values.195.cycle]
on = 900
off = 1100
delay = 1200

[values.196.cycle]
on = 900
off = 1100
delay = 1600

[values.197.cycle]
on = 900
off = 1100
delay = 0

[values.198.cycle]
on = 900
off = 1100
delay = 400

[values.199.cycle]
on = 900
off = 1100
delay = 800

[values.200.cycle]
on = 900
off = 1100
delay = 1200

[values.205.cycle]
on = 900
off = 1100
delay = 1600

[values.207.cycle]
on = 900
off = 1100
delay = 0

[values.208.cycle]
on = 900
off = 1100
delay = 400

[values.210.cycle]
on = 900
off = 1100
delay = 800

[values.226.cycle]
on = 900
off = 1100
delay = 1200

[values.227.cycle]
on = 900
off = 1100
delay = 1600

[values.229.cycle]
on = 900
off = 1100
delay = 0

[values.232.cycle]
on = 900
off = 1100
delay = 400

[values.233.cycle]
on = 900
off = 1100
delay = 800

[values.235.cycle]
on = 900
off = 1100
delay = 1200

[values.236.cycle]
on = 900
off = 1100
delay = 1600

[values.241.cycle]
on = 900
off = 1100
delay = 0

[values.248.cycle]
on = 900
off = 1100
delay = 400

[values.250.cycle]
on = 900
off = 1100
delay = 800

[values.253.cycle]
on = 900
off = 1100
delay = 1200

[values.255.cycle]
on = 900
off = 1100
delay = 1600

[values.259.cycle]
on = 900
off = 1100
delay = 0

[values.260.cycle]
on = 900
off = 1100
delay = 400

[values.264.cycle]
on = 900
off = 1100
delay = 800

[values.266.cycle]
on = 900
off = 1100
delay = 1200

[values.273.cycle]
on = 900
off = 1100
delay = 1600

[values.277.cycle]
on = 900
off = 1100
delay = 0

[values.283.cycle]
on = 900
off = 1100
delay = 400

[values.285.cycle]
on = 900
off = 1100
delay = 800

[values.287.cycle]
on = 900
off = 1100
delay = 1200

[values.292.cycle]
on = 900
off = 1100
delay = 1600

[values.293.cycle]
on = 900
off = 1100
delay = 0

[values.297.cycle]
on = 900
off = 1100
delay = 400

[values.298.cycle]
on = 900
off = 1100
delay = 800

[values.307.cycle]
on = 900
off = 1100
delay = 1200

[values.314.cycle]
on = 900
off = 1100
delay = 1600

[values.315.cycle]
on = 900
off = 1100
delay = 0

[values.326.cycle]
on = 900
off = 1100
delay = 400

[values.327.cycle]
on = 900
off = 1100
delay = 800

[values.328.cycle]
on = 900
off = 1100
delay = 1200

[values.338.cycle]
on = 900
off = 1100
delay = 1600

[values.340.cycle]
on = 900
off = 1100
delay = 0

[values.345.cycle]
on = 900
off = 1100
delay = 400

[values.346.cycle]
on = 900
off = 1100
delay = 800

[values.348.cycle]
on = 900
off = 1100
delay = 1200

[values.355.cycle]
on = 900
off = 1100
delay = 1600

[values.360.cycle]
on = 900
off = 1100
delay = 0

[values.362.cycle]
on = 900
off = 1100
delay = 400

[values.368.cycle]
on = 900
off = 1100
delay = 800

[values.369.cycle]
on = 900
off = 1100
delay = 1200

[values.378.cycle]
on = 900
off = 1100
delay = 1600

[values.388.cycle]
on = 900
off = 1100
delay = 0

[values.395.cycle]
on = 900
off = 1100
delay = 400

[values.397.cycle]
on = 900
off = 1100
delay = 800

[values.400.cycle]
on = 900
off = 1100
delay = 1200

[values.404.cycle]
on = 900
off = 1100
delay = 1600
