[values.126]
enabled = true
steps = 1000
required_steps = 1000
recipe = "CarbonDioxideCondensation"
products_finished = 0
status = "Running"
input_slots = [0, 1, 2]
output_slots = [3, 4]

[values.133]
enabled = true
steps = 1000
required_steps = 1000
recipe = "CarbonDioxideCondensation"
products_finished = 0
status = "Running"
input_slots = [0, 1, 2]
output_slots = [3, 4]
