[values.46]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.50]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.52]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.56]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 61

[values.59]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.60]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.64]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.70]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 61

[values.84]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.88]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.90]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.95]
is_on = false
is_rcs = false
thrust = 320000.0
last_controlled_by = 61

[values.98]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.99]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 61

[values.106]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.112]
is_on = false
is_rcs = false
thrust = 320000.0
last_controlled_by = 61

[values.114]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 61

[values.132]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 61

[values.174]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.176]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.182]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.184]
is_on = false
is_rcs = false
thrust = 320000.0
last_controlled_by = 191

[values.186]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.187]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.188]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.195]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.196]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 191

[values.225]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.237]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.238]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.242]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.243]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.244]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.245]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.246]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.247]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.252]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.254]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.255]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.257]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.273]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.274]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.276]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.279]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.280]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.282]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.283]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.288]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.295]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.297]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.300]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.302]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.306]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.307]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.311]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.313]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.320]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.324]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.330]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.332]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.334]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.339]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.340]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.344]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.345]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.348]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 294

[values.354]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.361]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.362]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.373]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.374]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.375]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.385]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.387]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.392]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.393]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.395]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.402]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.407]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.409]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.415]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.416]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.419]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 294

[values.425]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.435]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.436]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 294

[values.440]
is_on = false
is_rcs = false
thrust = 400000.0
last_controlled_by = 294

[values.442]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.444]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.447]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294

[values.451]
is_on = false
is_rcs = true
thrust = 4000.0
last_controlled_by = 294
