[values.50.cycle]
on = 900
off = 1100
delay = 0

[values.54.cycle]
on = 900
off = 1100
delay = 400

[values.56.cycle]
on = 900
off = 1100
delay = 800

[values.63.cycle]
on = 900
off = 1100
delay = 1200

[values.64.cycle]
on = 900
off = 1100
delay = 1600

[values.68.cycle]
on = 900
off = 1100
delay = 0

[values.88.cycle]
on = 900
off = 1100
delay = 400

[values.92.cycle]
on = 900
off = 1100
delay = 800

[values.94.cycle]
on = 900
off = 1100
delay = 1200

[values.102.cycle]
on = 900
off = 1100
delay = 1600

[values.110.cycle]
on = 900
off = 1100
delay = 0

[values.118.cycle]
on = 900
off = 1100
delay = 400

[values.185.cycle]
on = 900
off = 1100
delay = 800

[values.189.cycle]
on = 900
off = 1100
delay = 1200

[values.191.cycle]
on = 900
off = 1100
delay = 1600

[values.198.cycle]
on = 900
off = 1100
delay = 0

[values.199.cycle]
on = 900
off = 1100
delay = 400

[values.203.cycle]
on = 900
off = 1100
delay = 800

[values.222.cycle]
on = 900
off = 1100
delay = 1200

[values.226.cycle]
on = 900
off = 1100
delay = 1600

[values.228.cycle]
on = 900
off = 1100
delay = 0

[values.236.cycle]
on = 900
off = 1100
delay = 400

[values.243.cycle]
on = 900
off = 1100
delay = 800

[values.251.cycle]
on = 900
off = 1100
delay = 1200

[values.321.cycle]
on = 900
off = 1100
delay = 1600

[values.323.cycle]
on = 900
off = 1100
delay = 0

[values.329.cycle]
on = 900
off = 1100
delay = 400

[values.333.cycle]
on = 900
off = 1100
delay = 800

[values.334.cycle]
on = 900
off = 1100
delay = 1200

[values.335.cycle]
on = 900
off = 1100
delay = 1600

[values.342.cycle]
on = 900
off = 1100
delay = 0

[values.343.cycle]
on = 900
off = 1100
delay = 400

[values.370.cycle]
on = 900
off = 1100
delay = 800

[values.371.cycle]
on = 900
off = 1100
delay = 1200

[values.374.cycle]
on = 900
off = 1100
delay = 1600

[values.378.cycle]
on = 900
off = 1100
delay = 0

[values.381.cycle]
on = 900
off = 1100
delay = 400

[values.383.cycle]
on = 900
off = 1100
delay = 800

[values.387.cycle]
on = 900
off = 1100
delay = 1200

[values.390.cycle]
on = 900
off = 1100
delay = 1600

[values.406.cycle]
on = 900
off = 1100
delay = 0

[values.408.cycle]
on = 900
off = 1100
delay = 400

[values.414.cycle]
on = 900
off = 1100
delay = 800

[values.418.cycle]
on = 900
off = 1100
delay = 1200

[values.419.cycle]
on = 900
off = 1100
delay = 1600

[values.420.cycle]
on = 900
off = 1100
delay = 0

[values.427.cycle]
on = 900
off = 1100
delay = 400

[values.428.cycle]
on = 900
off = 1100
delay = 800

[values.457.cycle]
on = 900
off = 1100
delay = 1200

[values.469.cycle]
on = 900
off = 1100
delay = 1600

[values.470.cycle]
on = 900
off = 1100
delay = 0

[values.474.cycle]
on = 900
off = 1100
delay = 400

[values.475.cycle]
on = 900
off = 1100
delay = 800

[values.476.cycle]
on = 900
off = 1100
delay = 1200

[values.477.cycle]
on = 900
off = 1100
delay = 1600

[values.478.cycle]
on = 900
off = 1100
delay = 0

[values.479.cycle]
on = 900
off = 1100
delay = 400

[values.484.cycle]
on = 900
off = 1100
delay = 800

[values.486.cycle]
on = 900
off = 1100
delay = 1200

[values.487.cycle]
on = 900
off = 1100
delay = 1600

[values.489.cycle]
on = 900
off = 1100
delay = 0

[values.505.cycle]
on = 900
off = 1100
delay = 400

[values.506.cycle]
on = 900
off = 1100
delay = 800

[values.508.cycle]
on = 900
off = 1100
delay = 1200

[values.511.cycle]
on = 900
off = 1100
delay = 1600

[values.512.cycle]
on = 900
off = 1100
delay = 0

[values.514.cycle]
on = 900
off = 1100
delay = 400

[values.515.cycle]
on = 900
off = 1100
delay = 800

[values.520.cycle]
on = 900
off = 1100
delay = 1200

[values.527.cycle]
on = 900
off = 1100
delay = 1600

[values.529.cycle]
on = 900
off = 1100
delay = 0

[values.532.cycle]
on = 900
off = 1100
delay = 400

[values.534.cycle]
on = 900
off = 1100
delay = 800

[values.538.cycle]
on = 900
off = 1100
delay = 1200

[values.539.cycle]
on = 900
off = 1100
delay = 1600

[values.543.cycle]
on = 900
off = 1100
delay = 0

[values.545.cycle]
on = 900
off = 1100
delay = 400

[values.552.cycle]
on = 900
off = 1100
delay = 800

[values.556.cycle]
on = 900
off = 1100
delay = 1200

[values.562.cycle]
on = 900
off = 1100
delay = 1600

[values.564.cycle]
on = 900
off = 1100
delay = 0

[values.566.cycle]
on = 900
off = 1100
delay = 400

[values.571.cycle]
on = 900
off = 1100
delay = 800

[values.572.cycle]
on = 900
off = 1100
delay = 1200

[values.576.cycle]
on = 900
off = 1100
delay = 1600

[values.577.cycle]
on = 900
off = 1100
delay = 0

[values.586.cycle]
on = 900
off = 1100
delay = 400

[values.593.cycle]
on = 900
off = 1100
delay = 800

[values.594.cycle]
on = 900
off = 1100
delay = 1200

[values.605.cycle]
on = 900
off = 1100
delay = 1600

[values.606.cycle]
on = 900
off = 1100
delay = 0

[values.607.cycle]
on = 900
off = 1100
delay = 400

[values.617.cycle]
on = 900
off = 1100
delay = 800

[values.619.cycle]
on = 900
off = 1100
delay = 1200

[values.624.cycle]
on = 900
off = 1100
delay = 1600

[values.625.cycle]
on = 900
off = 1100
delay = 0

[values.627.cycle]
on = 900
off = 1100
delay = 400

[values.634.cycle]
on = 900
off = 1100
delay = 800

[values.639.cycle]
on = 900
off = 1100
delay = 1200

[values.641.cycle]
on = 900
off = 1100
delay = 1600

[values.647.cycle]
on = 900
off = 1100
delay = 0

[values.648.cycle]
on = 900
off = 1100
delay = 400

[values.657.cycle]
on = 900
off = 1100
delay = 800

[values.667.cycle]
on = 900
off = 1100
delay = 1200

[values.674.cycle]
on = 900
off = 1100
delay = 1600

[values.676.cycle]
on = 900
off = 1100
delay = 0

[values.679.cycle]
on = 900
off = 1100
delay = 400

[values.683.cycle]
on = 900
off = 1100
delay = 800
