use bary_core::prelude::*;
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq)]
pub enum OnClick {
    Exit,
    Save,
    Load,
    ToggleDrawMode,
    ClearTracks,
    CreateGroup,
    ClearOrbits,
    SelectedCount,
    AutopilotingCount,
    PilotOrbiter,
    TogglePause,
    World,
    GlobalOrbit(usize),
    DeleteOrbit(usize),
    DeleteOrbiter,
    ClearMission,
    CommitMission,
    ClearTarget,
    ClearPilot,
    SelectPart(String),
    ToggleLayer(PartLayer),
    LoadVehicle(PathBuf),
    DismissExitDialog,
    ConfirmExitDialog,
    TogglePartsMenuCollapsed,
    ToggleVehiclesMenuCollapsed,
    ToggleLayersMenuCollapsed,
    ToggleVehicleInfo,
    IncrementThrottle(i32),
    OpenNewCraft,
    WriteVehicleToImage,
    RotateCraft,
    NormalizeCraft,
    ToggleThruster(usize),
    ReloadGame,
    ClearContents(PartId),
    SetControllerPolicy(VehicleControlPolicy),
    ZoomToVehicle,
    ZoomToOrbit,
    CloseWindow(u32),
    Nullopt,
}
